Repository ISPP-2425-G9/frontend, pull requests merged in 2025-04, with the labels that each got.

#116 Fix plan update problem
  .gitignore
  app/_util/useAuth.tsx
  app/login/index.tsx
  app/messages/listMyMessages.tsx
  app/subscribe/index.tsx
  components/PaymentModal.tsx
  components/PlanCard.tsx
  components/SecureField.tsx
  components/SuccessModal.tsx
  components/SucessCancelModel.tsx
  hooks/useAuth.ts
  hooks/useResponsiveLayout.ts
Labels: bug, frontend

#115 Feedback from pilot users
  app/_layout.tsx
  app/certificate/index.tsx
  app/login/index.tsx
  app/obituaries/loadCertificate.tsx
  app/profile/index.tsx
  app/register/index.tsx
  app/services/index.tsx
  components/CustomModal.tsx
  components/CustomNavbar.tsx
  components/CustomTextInput.tsx
  components/DeleteAccountButton.tsx
  components/LogoutButton.tsx
  components/Notification.tsx
  components/TextInputArraysForm.tsx
Labels: bug, frontend

#129 Improve contact page
  app/contact/index.tsx
  components/__tests__/contact-test.tsx
  package-lock.json
Labels: frontend

#130 Add footer
  app/_layout.tsx
  app/home.tsx
  components/AnimatedIcon.tsx
  components/Footer.tsx
Labels: enhancement, frontend

#131 Home page view
  app/_layout.tsx
  app/about/index.tsx
  app/home.tsx
  app/profile/index.tsx
  components/CustomNavbar.tsx
  components/Footer.tsx
  components/__tests__/about-test.tsx
  package-lock.json
  package.json
Labels: enhancement, frontend

#137 Feedback from pilot users
  app/admin/certificatesManagement.tsx
  app/admin/editUser.tsx
  app/certificate/index.tsx
  app/contacts/index.tsx
  app/messages/index.tsx
  app/obituaries/createObituary.tsx
  app/obituaries/loadCertificate.tsx
  app/obituaries/selectContacts.tsx
  app/profile/index.tsx
  app/services/index.tsx
  components/CustomTextInput.tsx
  components/__tests__/contact-test.tsx
Labels: frontend
